### ISSUE TITLE
Pads on same LAN syncing incorrectly

### ISSUE THREAD

**Issue by mplorentz** [noffle/hyperpad-desktop#2] opened 2018-04-06 21:44 UTC
I am seeing my pads get out of sync pretty quickly when viewing a note on two clients.

Steps to reproduce:
1. Launch Hyperpad on two devices.
2. Create a new pad on one device.
3. Type a "1" in the text field.
4. Delete the "1" with a backspace.
5. Type a "2" in the text field.
6. Copy the note hash and paste it into the "Add pad from hash" box and hit enter.

Expected:
Note on both devices is "2".

Actual:
Note on device 2 shows "21".

**Comment by hackergrrl** [comment] 2018-04-20 22:52
I can successfully reproduce! It turns out local handling of remote deletions was *totally* broken. I've pushed a fix for this, and it seems to be working. (48647abaef6d967a3d67b707b8fa93fdbc5e14c4)

1.0.1 -- could you reopen if this continues?

**Closed as completed by hackergrrl** 2018-04-20 22:52 UTC

**Comment by mplorentz** [comment] 2018-04-23 18:29
Thanks! This fixed it for me.
